#!/usr/bin/env python

import os, sys
from database import Database

if __name__ == '__main__':
    db = Database('games.db')
    try:
        game = db[sys.argv[1]]
        print "%s:" % game.name
        print "  title = %s" % game.title
        print "  year = %s" % game.year
        print "  manufacturer = %s" % game.manufacturer
        print "  status = %s" % game.status
    except KeyError:
        print "%s not found in games database" % sys.argv[1]
    except Exception, e:
        print "Error: %s" % str(e)
    db.close()
