#!/usr/bin/env python

import pygtk
pygtk.require('2.0')
import gtk
from window import MainWindow
from database import Database

if __name__ == "__main__":
    window = MainWindow(Database('games.db'))
    gtk.main()
